version: "3.8"

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mrshyspy
      MONGO_INITDB_ROOT_PASSWORD: 5399
    volumes:
      - C:/mongo-data:/data/db

  app1:
    image: mrshyspy/my-app:1.0
    ports:
      - "3001:3000"
    environment:
      MONGO_URL: mongodb://mrshyspy:5399@mongo:27017/mydb?authSource=admin
    depends_on:
      - mongo

  app2:
    image: mrshyspy/my-app:1.0
    ports:
      - "3002:3000"
    environment:
      MONGO_URL: mongodb://mrshyspy:5399@mongo:27017/mydb?authSource=admin
    depends_on:
      - mongo

  app3:
    image: mrshyspy/my-app:1.0
    ports:
      - "3003:3000"
    environment:
      MONGO_URL: mongodb://mrshyspy:5399@mongo:27017/mydb?authSource=admin
    depends_on:
      - mongo

  nginx:
    image: nginx:latest
    container_name: nginx-loadbalancer
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
      - app3
